platform:ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'BlinkLabel_Example' do
  pod 'BlinkLabel', :path => '../'

  target 'BlinkLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
